### ISSUE TITLE
Music will not play

### ISSUE THREAD

**Issue by kjbennicke** [Tabletop-RPG-Music/tabletop-rpg-music#1]
Currently running version 0.7.9 of Foundry and version 1.14.2.
When once  Playlist has been imported, some tracks will play in the playlist and some will not.
In this case I had imported the epic music Playlist and the only song that would play is "The Grey Hunt". This occured on two separate servers running the same versions.

**Comment by kjbennicke** [comment]
I tested other playlists and the same thing seems to occur with multiple tracks on other playlists

**Comment by Tabletop-RPG-Music** [comment]
Hmm, that is strange. I've not had anyone else mention this issue. I'm going to be updating the module quite soon with 10 more tracks, once that update is out could you test again and let me know if you run into the same issue?

Also, could you check to see if the tracks that have 'large file streaming' selected are the ones that aren't playing?

**Comment by kjbennicke** [comment]
I sure can! I'll test the files either the 'large file streaming' and let you know and will report back after your next update drops.

**Comment by Tabletop-RPG-Music** [comment]
Update is live, let me know if everyone works or not!

________________________________

**Comment by Tabletop-RPG-Music** [comment]
I've noticed an issue where if I quickly switch tracks multiple times in a row, eventually the music will stop playing on one of the tracks. Then I'll have to wait ages for it to start playing. It's probably something to do with the way Foundry handles larger audio files, which looks to be changing in the 0.8 Foundry release, so pehaps this is a bug that won't be around for long. Anyway, let me know how you get on!

**Comment by kjbennicke** [comment]
Hey, So I updated the module to 1.3.0 and made sure each track had "Large File Streaming" turned on. I am still experiencing the issue.
I had done some research on the subreddit and I think I might be experiencing the fast switching issue you had noted. 
Others have had those issues with other audio and it is apparently RAM related on the hosting computer/server. It also should be noted my Foundry server is running on my friends private server as a Node server and not one of the recommended hosting services. Which may not experience the same issue. 
I think hopefully Foundry 0.8.0 will solve this as I know they are Moving away from Howler JS.
If you need more info let me know.

Thanks for the quick response. The tracks that do play are amazing! 
Looking forward to hearing the others.
