### ISSUE TITLE
Integrate with Moulinette

### ISSUE THREAD

**Issue by ghost91-** [Tabletop-RPG-Music/tabletop-rpg-music#2]
[Moulinette](https://github.com/SvenWerlen/moulinette-core) is a module that can be used to manage all kinds of different assets, including audio. It provides a very convenient interface to access files, drag them onto the scene, and create playlists from audio files. Moulinette provides a very easy way for content modules to integrate with it and it would be great if Tabletop RPG Music could do so.

The documentation about how this integration works can be found here: https://github.com/SvenWerlen/moulinette-core/blob/main/docs/README.md#how-to-index-assets-provided-by-other-modules

However, it is extremely easy, all that would be needed is to include a small JavaScript file in your module:

```js
Hooks.once("ready", async function () {
  if(game.moulinette) {
    game.moulinette.sources.push({ type: "sounds", publisher: "Tabletop RPG Music", pack: "Tabletop RPG Music", source: "data", path: "modules/tabletop-rpg-music/music" })
  }
});
```

And of course you would need to include this JavaScript file in your `module.json`.

I really hope you consider adding this as it would be a tremendous help for users of both Moulinette and Tabletop RPG Music. I would also be willing to simply create a Pull Request to add this if it sounds like a good idea to you in general :)

**Comment by Tabletop-RPG-Music** [comment]
Hey there! I've heard good things about Moulinette, I'd be up for adding this. Feel free to create the pull request.

**Comment by Tabletop-RPG-Music** [comment]
@ghost91- If you get the chance could you test out whether the Moulinette integration worked? Thanks

**Comment by ghost91-** [comment]
Sure, will do so!

**Comment by ghost91-** [comment]
Tested it, it's working great:
![Bildschirmfoto am 2021-10-05 um 12 27 48](https://user-images.githubusercontent.com/236845/136006389-422a5069-0f28-4144-9d01-70c2e33f84ed.png)

**Comment by Tabletop-RPG-Music** [comment]
Brilliant! 🙂 Sorry it took me so long!

________________________________
