### ISSUE TITLE
Won't show in world modules. 

### ISSUE THREAD

**Issue by alxdean** [Tabletop-RPG-Music/tabletop-rpg-music#5]
Hi, I'm self-hosting D&D5e v1.4.2 on FoundryVTT 0.8.8 and after installing the module it won't show in my available modules in the world. So I can't activate the compendium. Any Idea why that could be?

**Comment by alxdean** [comment]
Forget I asked. It requires a core upgrade to 0.8.9 which I'm not ready to do yet. Too many Modules could break. Not risking it.

**Comment by alxdean** [comment]
not going to upgrade to 0.8.9. Too risky.

**Comment by Tabletop-RPG-Music** [comment]
Fair enough! I've not tested it in earlier versions but it's a fairly simple module so I would've thought it would have worked.

________________________________

**Comment by alxdean** [comment]
Maybe you can republish and take down the minimum core version a notch? I'd love to give your module a try. Yours is the very first that mandates 0.8.9 in all the mods I have installed.
________________________________

**Comment by Tabletop-RPG-Music** [comment]
Okay, I've changed the minimum core version down to 0.8.8 in both the json file + on the foundry package site. I've kept the version number the same though, but hopefully it will still push those changes.

________________________________

**Comment by alxdean** [comment]
That worked! Thank you so much. looking forward to listening to your work
and using it in my campaign.
*-- *
*Alex Dean*

Phone:  +41 774632194  | *Web: http://www.linkedin.com/in/alxdean
<http://www.linkedin.com/in/alxdean>  *Skype:  alxdean

**Comment by Tabletop-RPG-Music** [comment]
Awesome, glad it worked!
________________________________
